# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x04xxdb\".\n\x0b\x41uthRequest\x12\x0e\n\x06\x64\x62name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"j\n\rCommonRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x06op_key\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0bput_payload\x18\x03 \x01(\x0cH\x01\x88\x01\x01\x42\t\n\x07_op_keyB\x0e\n\x0c_put_payload\"\xa8\x01\n\x0e\x43ommonResponse\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.xxdb.CommonResponse.Status\x12\x14\n\x0c\x61uth_payload\x18\x02 \x01(\t\x12\x15\n\rerror_payload\x18\x03 \x01(\t\x12\x13\n\x0bget_payload\x18\x04 \x01(\x0c\"\'\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_AUTHREQUEST']._serialized_start=23
  _globals['_AUTHREQUEST']._serialized_end=69
  _globals['_COMMONREQUEST']._serialized_start=71
  _globals['_COMMONREQUEST']._serialized_end=177
  _globals['_COMMONRESPONSE']._serialized_start=180
  _globals['_COMMONRESPONSE']._serialized_end=348
  _globals['_COMMONRESPONSE_STATUS']._serialized_start=309
  _globals['_COMMONRESPONSE_STATUS']._serialized_end=348
# @@protoc_insertion_point(module_scope)
